---
version: 2
publish: &publish
  working_directory: ~/my-app
  docker:
    - image: cimg/node:14.17.6
  steps:
    - checkout

    - run:
        name: Installing dependencies
        command: npm install

    - run:
        name: Login into Expo
        command: npx expo-cli login -u $EXPO_USERNAME -p $EXPO_PASSWORD

jobs:
  publish_android_to_expo:
    environment:
      TARGET_ANDROID: apk
    <<: *publish
    steps:
      - run:
          name: Publish Android to Expo
          no_output_timeout: 30m
          command: npx expo-cli build:android -t $TARGET_ANDROID --non-interactive #--release-channel $EXPO_RELEASE_CHANNEL

  publish_ios_to_expo:
    environment:
      TARGET_IOS: simulator
    <<: *publish
    steps:
      - run:
        name: Publish IOS to Expo
        no_output_timeout: 30m
        command: npx expo-cli build:ios -t $TARGET_IOS --non-interactive #--release-channel $EXPO_RELEASE_CHANNEL

workflows:
  version: 2
  my_app:
    jobs:
      - publish_android_to_expo
      - publish_ios_to_expo